### ISSUE TITLE
Warning: Installation path /home/opiccolo/.local/bin not found on the PATH environment variable

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-comandi-conversione#16]
@pablopers riceve questo warning dopo l'installazione

**Comment by danse** [comment]
@pablopers visto che ricevi quel warning, credo che `converti`, `pandoc-to-sphinx` e gli altri comandi non siano usabili sul tuo sistema perché la cartella dove sono stati aggiunti non fa parte del `$PATH` quindi non sono visibili

**Comment by danse** [comment]
il `$PATH` è un'elenco di cartelle che istruisce il tuo sistema sul dove trovare i comandi che lanci

**Comment by danse** [comment]
puoi controllare il contenuto attuale del `$PATH` eseguendo:

    $ echo $PATH

**Comment by danse** [comment]
il warning ti dice che le cose installate con Stack vanno in una cartella che non è parte del tuo path, quindi non potrai usarli

**Comment by pablopers** [comment]
```
opiccolo@dbckan02cl:~/docs-italia-comandi-conversione$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

**Comment by danse** [comment]
nelle istruzioni per l'installazione di Stack si spiega come aggiornare il path qui https://docs.haskellstack.org/en/stable/GUIDE/#downloading-and-installation ma _your mileau may change_ quindi vediamo cosa serve nel tuo caso ... innanzitutto prova ad aggiornare il `.bashrc` come suggeriscono loro e lanciare una nuova console e dopo ripetere `echo $PATH` ... dovrebbe essere diverso e contenere la cartella con i nostri comandi

**Comment by danse** [comment]
ho aggiunto una breve introduzione al tema sperando che ne aiuti la comprensione https://github.com/italia/docs-italia-comandi-conversione/blob/master/doc/aggiornamento-path.md

**Comment by pablopers** [comment]
lanciato il comando `echo 'export PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc` 
riavviata la console 
lanciati i comandi 
Nessun Warning! 
perfetto Grazie

**Comment by danse** [comment]
grande grazie a te! :raised_hands:
