### ISSUE TITLE
Considerazioni sulla licenza AGPL

### ISSUE THREAD

**Issue by massimo-zaniboni** [italia/docs-italia-comandi-conversione#18]
Da una discussione in IRC #haskell-it con Francesco.

## Utilizzo della AGPL lato developer

Ad essere (eccessivamente) precisi ogni file del progetto dovrebbe riportare in testa l'indicazione che si sta usando la licenza AGPL, come riportato da https://www.gnu.org/licenses/gpl-howto.html 

```
 This file is part of Nome-Programma.

    Nome-Programma is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Nome-Programma is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Nome-Programma.  If not, see <http://www.gnu.org/licenses/>.
```

Consiglio invece di usare lo standard https://spdx.org/licenses/ usato anche dal progetto Linux, dove basta aggiungere in testa la singola linea:

```
# SPDX-License-Identifier: AGPL-3.0-or-later
```
I vantaggi:
* una sola linea, molto leggibile, e con una informazione utile (no boiler-plate)
* ci sono tool di gestione delle code-base che supportano SPDX
* piu\` progetti usano SPDX e piu\` SPDX si diffondera\`,  e mi sembra una buona cosa, dato che razionalizza un aspetto un po\' odioso degli header "legali"

## Utilizzo AGPL lato utente

E\` coerente con la filosofia Pandoc che anche il motore dei filtri sia rilasciato sotto GPL o AGPL, in modo che eventuali miglioramenti siano condivisi con tutti.

Pero\` i file di esempio che utilizzano i filtri, dovrebbero essere rilasciati sotto una licenza piu\` permissiva tipo MIT, dato che una volta estesi e utilizzati dagli utenti, possono contenere informazioni riservate come nomi di parti contrattuali o altro. Di fatto questi files sono piu\` nell'ambito del "documento" del singolo utente (quindi informazione privata/sensibile) che nell'ambito del progetto condiviso.

Usando SPDX basterebbe aggiungere in testa a questi files:

```
# SPDX-License-Identifier: MIT
``` 

e indicare nel README che i miglioramenti al progetto devono essere condivisi tramite AGPL, mentre i file di esempio possono essere liberamente utilizzati, e eventualmente indicare due directory diverse (progetto, e filtri di esempio) o indicare il differente header SPDX.

## MIT license

Tempo fa mi ero interessato a licenze che dicessero "fai quello che vuoi con questo file". Ho scoperto che per ragioni di differenti legislazioni e\` sorprendentemente difficile scrivere una licenza di questo tipo, e che quindi e\` sempre consigliato usare una licenza completa, seppur minimale, come MIT o BSD che dica chi e\` il copyright owner, che ci possono essere errori, che lui non e\` responsabile e che il lavoro puo\` essere liberamente usato. 

A dire il vero BSD e MIT aggiungono anche ``The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.`` Ma con SPDX si traduce nel lasciare il TAG in testa al file copiato, e tenere aggiornato il file AUTHORS e/o usare Git & C. per risalire a chi ha modificato cosa.

**Comment by rasky** [comment]
Ciao, grazie per i tuoi commenti.

La materia dell'uso e rilascio dell'open source nel contesto della PA è disciplinata in una soft-law chiamata "Linea Guida per l'Acquisizione e Riuso del Software", su cui abbiamo lavorato (Team Digitale + AgID) negli scorsi mesi e che uscirà in gazzetta ufficiale a breve e puoi trovare online in versione di bozza che è andata in consultazione pubblica qui:
https://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/

In particolare, l'allegato B si occupa dei tecnicismi di come effettuare la pubblicazione di codice open source, e al [paragrafo 4](https://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/attachments/allegato-b-guida-alla-pubblicazione-open-source-di-software-realizzato-per-la-pa.html#attribuzione-della-licenza-ed-individuazione-della-titolarita
) consiglia proprio l'utilizzo di SPDX in cima ad ogni file. Su questo penso che @danse possa procedere appena lo ritiene.

Per quanto riguarda la scelta della licenza, ovviamente è in capo al titolare del software che nel caso di questo repo è il Team Digitale della Presidenza del Consiglio (come anche visibile nel file [AUTHORS](https://github.com/italia/docs-italia-comandi-conversione/blob/master/AUTHORS)). Le Linee Guida di cui sopra hanno un obbligo (MUST) di scelta di [una qualunque licenza OSI](https://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/riuso-software/licenze-aperte-e-scelta-di-una-licenza.html#licenze-per-il-software-aperto) e consigliano (SHOULD) un [albero decisionale di default](https://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/riuso-software/licenze-aperte-e-scelta-di-una-licenza.html#scelta-di-una-licenza) che prevede alcune scelte di base.

Lascio comunque un'eventuale discussione in merito ad un cambio licenza a @ruphy.

**Comment by danse** [comment]
Grazie @massimo-zaniboni per la segnalazione sulle intestazioni e @rasky per la risposta puntuale ed i riferimenti. Quindi se ho capito bene il suggerimento è di usare una licenza più liberale per [i filtri](https://github.com/italia/docs-italia-pandoc-filters/tree/master/filters), per permetterne un uso più agevole all'interno delle amministrazioni. Il repo dei filtri contiene praticamente solo i filtri e i rispettivi test, quindi si tratterebbe di passare il repo ad una licenza più liberale. Invece della MIT potremmo usare la BSD 3 che è fra [le approvate dal Team](https://github.com/teamdigitale/licenses).

Ho notato che il copyright andava aggiornato al 2018, fatto nei tre repo. Segnalo anche che abbiamo [un repo con test di regressione](https://github.com/danse/docs-italia-test-conversione#documents-license) cioè veri e propri documenti, già pubblicati altrove, che sono rilasciati con licenza CC-BY 4.

Se siete d'accordo:
- [ ] aggiungerò headers SPDX ai repo di comandi e filtri
- [ ] cambierò la licenza dei filtri a BSD 3
- [ ] headers CC-BY-4 per la documentazione qui

L'ultimo punto si riferisce [alla cartella di documentazione](https://github.com/italia/docs-italia-comandi-conversione/tree/master/doc) in questo repo. È un luogo privilegiato per condividere e collaborare su documenti che vogliamo presentare agli utenti di questi comandi, ma potrebbero facilmente finire altrove su qualche wiki. Per esempio ci sono alcune note sull'uso della riga di comando, un'idea da presentare a `pandoc-discuss` per l'inserimento nel wiki di pandoc, ed una bozza di traduzione parziale in italiano del manuale di pandoc. Accetto volentieri consigli sui passaggi necessari prima di rimuovere contenuti dalla cartella ed incollarli altrove ... l'obiettivo è la massima fluidità per mantenere doc il più aggiornata possibile nei luoghi dove può meglio coinvolgere ed informare

**Comment by massimo-zaniboni** [comment]
Ops ho sbagliato repo (seguito il link sbagliato). In realtà mi riferivo a https://github.com/italia/docs-italia-pandoc-filters

Per esempio in questo filtro:

https://github.com/italia/docs-italia-pandoc-filters/blob/master/filters/filtro-acronimi.hs

un utente potrebbe fare copia e incolla e adattare parte del contenuto tipo

```
operazioni = (sostituzione ("ANPR" `e` "anpr" `diventa` "Anpr")) `e`
(sostituzione ("ANAS" `e` "anas" `diventa` "Anas"))
```

con operazioni di sostituzione per lui pertinenti, ma alcuni nomi potrebbero essere confidenziali e quindi l'ideale è che i filtri di esempio e/o di test siano liberamente modificabili sotto BSD3, invece che AGPL.

Ma intendiamoci è una finezza scritta solo perchè in #haskell.it si parlava del progetto (usa Haskell e Pandoc e sembra interessante/utile) e si è accennato alla licenza. Quindi solo per il gusto di discussione in generale. Nulla di veramente importante. Lato pratico uno può prendere qualunque esempio, modificarlo e usarlo senza che succeda nulla. :-)

**Comment by ruphy** [comment]
Ciao @massimo-zaniboni, grazie per i tuoi commenti.

A ciò che correttamente dice @rasky in merito alle licenze, aggiungo anche il link della policy interna del Team Digitale: https://github.com/teamdigitale/licenses/blob/master/README.it.md

Per quanto riguarda SPDX, è suggerito nelle nostre linee guida. Oltre all'header è possibile anche specificare un file che contiene il "catalogo" di file, in particolare per ciò che riguarda file binari, dove inserire un header sarebbe complesso.

Ciò che manca davvero, quando si rilasciano molti file binari, è un tool semplice per creare cataloghi in modo user-friendly, seguendo la specifica Debian: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

Detto questo, possiamo ovviamente farne uno a mano per questo repository. Mentre credo che il filtro debba rimanere sotto AGPL, direi che possiamo rilasciare i file di esempio sotto CC-BY, coerentemente con ciò che stiamo seguendo come politica interna per i file binari e la documentazione.

**Comment by danse** [comment]
Dunque ... non abbiamo files di esempio a parte i filtri. Mi sembra di capire che non abbiamo un consenso deciso sul cambio di licenza quindi lascerei la AGPL qui e nel repo dei filtri.

Questo tema del catalogo mi sembra molto interessante. Sbaglio o si può generare facilmente un catalogo dei files eseguendo `$ find * > catalog.txt`? Se è un'alternativa accettabile, preferirei questo piuttosto che aggiungere un header a ciascun file

**Comment by ruphy** [comment]
@danse in realtà la specifica è più semplice. Basta creare un file chiamato ´debian/copyright´ così formato:

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

Files: *
Copyright: The respective contributors, as shown by the AUTHORS file.
License: AGPL-3.0-or-later
```

**Comment by ruphy** [comment]
ho aggiunto il file di esempio con la licenza CC0 qui: https://github.com/teamdigitale/licenses/blob/master/debian/copyright

**Comment by danse** [comment]
bene, ho aggiunto i files. tutti soddisfatti? posso chiudere questa issue? :)
