### ISSUE TITLE
Vorrei: linkare automaticamente gli RFC

### ISSUE THREAD

**Issue by ioggstream** [italia/docs-italia-comandi-conversione#27]
## Riprodurre

- un testo contiene un riferimento ad `RFC7230`
- un testo contiene un riferimento ad una sottosezione, eg. `rfc7230#section-2.6`

## Vorrei

- che fosse renderizzato come un hyperlink, eg
 
  - `[RFC7230](https://tools.ietf.org/html/rfc7230)`
  - `[RFC7230](https://tools.ietf.org/html/rfc7230#section-2.6)`

**Comment by danse** [comment]
Grazie per l'idea @ioggstream, credo che questo si possa fare facilmente. Data la rappresentazione interna di un documento in pandoc, è un po' più complicato riconoscere qualcosa come `RFC 1234`, con uno spazio in mezzo. È comunque fattibile. Nel tuo documento ci sono casi simili?

**Comment by ioggstream** [comment]
imho una volta chiarito come dobbiamo scriverli (eg. rfc1234, rfc 1234, ..) ci si adegua.

per supportare le sezioni credo vada scritto tutto attaccato

**Comment by danse** [comment]
ecco qui https://github.com/italia/docs-italia-pandoc-filters/tree/master/filters#link-rfc, fammi sapere se funziona! :)
