### ISSUE TITLE
Struttura simile allo starter kit

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-comandi-conversione#31]
@pablopers mi fa notare che la struttura dei files nello starter kit è diversa da quella prodotta da `converti`:
```
+-- README.md
+-- index.rst
+-- _docs/
| +-- _img/
| | +-- cap1_img1.jpg
| | +-- cap2_img1.jpg
| | ...
| +-- cap1.rst
| +-- cap2.rst
| …
+-- conf.py
+-- LICENSE
+-- AUTHORS
+-- requirements.txt
+-- document_settings.yml
```
È più facile avvantaggiarsi di `converti` se i files prodotti sono in una struttura coerente con lo starter kit. Quanto a `README`, `LICENSE`, `AUTHORS` etcetera non credo che `converti` abbia alcun ruolo, però potremmo rendere omogenee le cartelle che contengono le sezioni e le immagini.

- converti salva le sezioni in una cartella `index/` mentre nello starter kit abbiamo `_docs`
- converti salva le immagini in una cartella `index/media` mentre nello starter kit abbiamo `_docs/_img`

Prima di cambiare i nomi vorrei chiedere un riscontro a @pdavide e @atorin, perché ricordo che si è discusso di questo in uno dei canali. Non so se preferiamo `_docs`, `index` o altro per le sezioni, né sono sicuro che vogliamo mantenere il nome `_img`. Credo che nè gli underscores nè i nomi abbreviati agevolino la comprensibilità

**Comment by atorin** [comment]
@pdavide suggeriva di usare una struttura in cui i capitoli sono contenuti in cartelle separate, e devo dire che sono d'accordo. La struttura degli url in questo modo è più ordinata. 

Esempio:
```
+---- index.rst
+---- titolo-primo-capitolo
|   +---- index.rst
|   +---- primo-paragrafo.rst
|   +---- titolo-interessante.rst
|   +---- titolo-sezione.rst
+---- titolo-secondo-capitolo
|   +---- index.rst
|   +---- nuova-sezione.rst
|   +---- titolo-molto-molto-lungo.rst
+---- titolo-terzo-capitolo
    +---- index.rst
    +---- paragrafo-rivoluzionario.rst
    +---- paragrafo-tecnologico.rst
    +---- paragrafo-tradizionale.rst
```

Domanda: in che modo vogliamo organizzare le figure? Usiamo un'unica cartella a livello di root o diverse cartelle, una per ogni capitolo?

Ricordiamo che al momento pandoc salva le immagini convertite in un'unica cartella.

**Comment by pdavide** [comment]
La struttura a directory separate la consiglierei solo per documenti più strutturati (nel senso che hanno molti livelli di sezioni). Nel caso di documenti semplici un struttura lineare (tutto nella root) la preferisco (anche per motivi seo).

**Comment by pdavide** [comment]
Si Francesco, hai capito perfettamente!
Mi piace molto l’idea di avere un’opzione per il comando che permette di modificare la strutturazione dell’output!

**Comment by danse** [comment]
bene! grazie a tutti per i vostri contributi, questo mi da materiale per ristrutturare quasi completamente `pandoc-to-sphinx` in modo da risparmiare aggiustamenti manuali noiosi ai nostri utenti. questa discussione ha impatto su diverse issues in questo repo, le riorganizzerò. Nel frattempo ho creato italia/docs-italia-starter-kit#8 per non dimenticare di aggiornare anche lo starter kit. Visto che stiamo progressivamente definendo le convenzioni che vogliamo adottare, per adesso il tema delle immagini rimane aperto

**Comment by danse** [comment]
la soluzione di questa issue agevola #81 quindi ne approfitterò per aggiungere la divisione in capitoli semplici ed annidati ... visto che non abbiamo metriche automatizzabili, questo porterà ad una nuova opzione ed una nuova checkbox nel convertitore web
