### ISSUE TITLE
rinomino `risultati-conversione`

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-comandi-conversione#51]
visto che la cartella è gestita in modo da conterene più documenti

**Comment by danse** [comment]
@yakky questo richiede un aggiornamento nel convertitore web?

**Comment by yakky** [comment]
@danse si

**Comment by danse** [comment]
come vuoi che ci coordiniamo in questi casi? bastano le release notes o vuoi che stabiliamo un processo? nei package haskell, un cambiamento di uno dei primi due numeri indica un cambiamento non retrocompatibile. un po' come semantic version su quattro cifre, dove in A.B.C.D un cambiamento in A o B indica il cambiamento di un'interfaccia

**Comment by danse** [comment]
in generale penso di fare una release alla fine di ogni milestone, quindi settimanalmente. ho fatto eccezione con 0.5 perché mi sembrava bloccante

**Comment by yakky** [comment]
Sicuramente le release notes sono fondamentali, e se viene documentato accuratamente il cambiamento fatto + il semantic versioning si può stare tranquilli

**Comment by yakky** [comment]
Però ad es dalle release notes della 0.5 non capisco se cambia qualcosa  nel modo di chiamare o nell'output del comando :thinking:

**Comment by danse** [comment]
non mi sono impegnato particolarmente nella descrizione di 0.5 perché la sostanza è che adesso spero funzioni come ci aspettiamo. Nelle release notes in realtà non scrivo nulla, ed anche il changelog https://github.com/italia/docs-italia-comandi-conversione/blob/master/ChangeLog.md#05----luglio-26 è abbastanza stringato, mi rendo conto che sarà meglio scrivere un changelog più esplicito in futuro. Cambia sia il modo in cui viene fatto il parsing delle opzioni sia il risultato del comando.

- Il risultato del comando cambia secondo quanto chiesto da Davide e descritto in #26, questo dovrebbe portare un miglioramento nei risultati del convertitore web, senza che ti preoccupi di nulla
- il parsing delle opzioni cambia secondo quello che avevamo discusso in #59 

Oggi ho migliorato l'help del comando, questo è l'help che sarà disponibile dalla prossima versione:
```
 docs-italia-esempiformattazione-docs (master)*$ converti --help
converti - comando semplificato per la conversione di formato

Usage: converti (documento.ext [--collegamento-normattiva] [--celle-complesse]
                [--preserva-citazioni] [--dividi-sezioni] | documento.ext
                --opzioni-json ARG | --version)
  converte il documento in formato rST.
  Nel caso più semplice, potete convertire un documento lanciando:
  
      $ converti documento.ext
  
  La documentazione più dettagliata si trova al seguente indirizzo:
  https://github.com/italia/docs-italia-comandi-conversione/blob/master/doc/comandi/converti.md

Available options:
  --collegamento-normattiva
                           sostituisce i riferimenti alle leggi con links a
                           Normattiva
  --celle-complesse        evita errori nelle celle di tabella complesse
                           scrivendo righe molto lunghe
  --preserva-citazioni     evita di rimuovere le citazioni
  --dividi-sezioni         produce un file .rst per ogni capitolo
  --opzioni-json ARG       permette di indicare un file JSON da cui leggere le
                           opzioni di converti
  --version                mostra la versione dei comandi di conversione
  -h,--help                Show this help text
 docs-italia-esempiformattazione-docs (master)*$ 
```

Se c'è ancora qualcosa di poco chiaro sentiti libero di aprire una issue in proposito, ne approfitterò per migliorare la documentazione.
