### ISSUE TITLE
controllo conversione files di esempio

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-comandi-conversione#54]
@francescozaia ha notato che l'ODT di esempio crea problemi col convertitore web

- [x] verifico i problemi con i comandi
- [x] verifico che i files di esempio vengano convertiti correttamente
- [x] immagini nel markdown
- [x] verifico figure docx
- [x] documento problema figure odt

**Comment by danse** [comment]
`esempio.odt` viene convertito correttamente usando `converti --collegamento-normattiva --dividi-sezioni`, versione 0.4.1.2, anche se ho dei dubbi su immagine e tabella con didascalia

**Comment by danse** [comment]
```
 docs-italia-esempiformattazione-docs (master)*$ converti esempio.md --collegamento-normattiva --dividi-sezioni
[WARNING] Could not fetch resource 'media/image1.jpeg': replacing image with description
[WARNING] Could not fetch resource 'media/image1.jpeg': replacing image with description
 docs-italia-esempiformattazione-docs (master)*$ 
```

**Comment by danse** [comment]
questa issue si è rivelata più impegnativa e fruttuosa del
previsto. da un lato perché gli esempi di conversione non erano
aggiornati allo sviluppo sui comandi dell'ultimo mese, e dall'altro
lato perché mi sono reso conto che gli esempi sono importanti per
spiegare la conversione agli utenti e per condividere le priorità di
conversione. abbiamo diversi formati e diverse funzionalità, e tutto
si può chiaramente verificare e spiegare attraverso gli
esempi. comunque lo spazio di ricerca è ampio, le dimensioni sono:

- i diversi formati (per esempio html, odt, docx)
- le semantiche da convertire (per esempio didascalie, tabelle, grassetto corsivo)
- gli stadi di elaborazione (conversione, divisione in sezioni, collegamento a normattiva)

@atorin @pablopers se siete d'accordo vorrei collezionare alcune
issues in questi giorni e presentarvele nella maniera più chiara
possibile durante la riunione di valutazione, in modo da definire
insieme le priorità e poi assegnare le issues alle future
milestones. credo che possiamo mettere in piedi un semplice processo
di definizione delle priorità che sia scalabile anche all'aumentare
del numero di utenti

**Comment by atorin** [comment]
d'accordo, parliamone lunedì

**Comment by danse** [comment]
i files sono convertiti, l'errore riscontrato da @francescozaia era qualcosa di più macroscopico che nel frattempo abbiamo risolto (ho finalmente usato il convertitore web, è fantastico! :tada: ). Ne ho approfittato per fare una mappatura dettagliata delle differenze di conversione, raggruppate con la label "esempi formattazione" https://github.com/italia/docs-italia-comandi-conversione/labels/esempi%20di%20formattazione

per verificare le differenze ho usato:
```
$ converti --preserva-citazioni esempio.html
$ diff esempio.rst risultati-conversione/esempio/documento.rst 
```

versione 0.5 dei comandi
