### ISSUE TITLE
errore nell'uso delle opzioni json

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-comandi-conversione#59]
```
 docs-italia-esempiformattazione-docs (master)*$ converti esempio.docx --opzioni-json opzioni-converti.json 
Invalid option `--opzioni-json'

Usage: converti ([documento.ext] [--collegamento-normattiva] [--celle-complesse]
                [--preserva-citazioni] [--dividi-sezioni] | [--opzioni-json ARG]
                | [--version])
```

chiedo scusa @yakky, avrei dovuto testare meglio. Sei già incappato in questo errore?

**Comment by danse** [comment]
risolvere questo mi porta a ristrutturare le opzioni. attualmente il documento su cui `converti` agisce è opzionale, con un valore di default `documento.docx`. credo che non abbia senso, lo renderò un argomento obbligatorio

**Comment by danse** [comment]
attualmente è possibile specificare il documento tramite un campo `documento` nel JSON, ma non penso serva a granché ... credo sia meglio lanciare `converti documento.ext --opzioni-json opzioni.json`

**Comment by danse** [comment]
:thinking: più che un bug è in realtà una scelta di interfaccia che mi sembra molto infelice, ma aspetto l'opinione di @yakky

**Comment by danse** [comment]
ovviamente possiamo anche continuare a supportare `documento` nel JSON, ed aggiungere la possibilità di indicare il documento come argomento ... gli utenti però in quel caso vorrebbero sapere quale valore ha il sopravvento. mi sembra una complicazione che non serve a granchè

**Comment by yakky** [comment]
si, concordo. ha senso rendere obbligatorio il path del documento e togliere l'attributo `documento` dal json, mi sembra più lineare

**Comment by danse** [comment]
hey, il problema è risolto nell'ultima release, così non siamo bloccati nel convertitore web! https://github.com/italia/docs-italia-comandi-conversione/releases/tag/v0.5 :)
