### ISSUE TITLE
Opzioni brevi per `converti`

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-comandi-conversione#60]
Dopo cinque o sei usi del comando, le opzioni così lunghe mi hanno già stancato ... è il momento di inventarsi delle alternative brevi che abbiano un senso. Propongo:

- `-n` per `--collegamento-normattiva`
- `-s` per `--dividi-sezioni` (anche Sphinx)
- `-j` per `--opzioni-json`

Le altre opzioni le uso più raramente, credo si possano tenere lunghe.

@atorin @pablopers @yakky vi sembrano scelte sensate?

**Comment by yakky** [comment]
se funzionano le opzioni json per me è indifferente dal punto di vista pratico
A lviello concettuale preferisco i comandi che mi offrono entrambe le versioni

**Comment by atorin** [comment]
Anche io non ho particolari preferenze. 
Riguardo alla scelta delle lettere, mi sembra più che sensata.

**Comment by danse** [comment]
sisi supporteremo sia la versione lunga sia la corta, lo davo per scontato ... si trattava per lo più della scelta delle lettere. grazie!

**Comment by danse** [comment]
non credo abbia senso investire nell'interfaccia dei comandi in questa fase del progetto visto che l'interfaccia principale che proporremo agli utenti è quella web. inoltre aggiornare l'interfaccia dei comandi richiede aggiornamenti al convertitore web, che invece preferiamo tenere stabile per concentrarci su attività che portino un beneficio più tangibile. tolgo questa issue dalla milestone
