### ISSUE TITLE
Sottotitolo

### ISSUE THREAD

**Issue by atorin** [italia/docs-italia-comandi-conversione#71]
La formattazione `subtitle` dovrebbe essere convertita nella direttiva `highlights` di rst. 

Al momento i sottotitoli vengono ignorati dal convertitore (vedi file allegati).

[sottotitolo.docx](https://github.com/italia/docs-italia-comandi-conversione/files/2235827/sottotitolo.docx)

[sottotitolo.odt.zip](https://github.com/italia/docs-italia-comandi-conversione/files/2235829/sottotitolo.odt.zip)

**Comment by danse** [comment]
questo riguarda gli esempi di formattazione, vero? credo che vorremo dare priorità a questo tipo di issues, aggiungo la label

**Comment by danse** [comment]
è un problema su cui ero già incappato, non mi piace l'interfaccia di pandoc in questo caso ma non sono riuscito a convincere gli altri https://github.com/jgm/pandoc/issues/4583 ... c'è questa idea di metadata nella comunità pandoc che è un po' controversa.

per me la cosa assurda, dal punto di vista dell'interfaccia, è che del contenuto venga ignorato perché ha un preciso stile. Per come la vedono gli altri, invece, i metadati vengono applicati solo come specificato in un eventuale template ... beh senza stare a farla troppo lunga, credo che possiamo usare un nostro template in `converti` per essere sicuri che il sottotitolo non venga omesso.

Quanto al metterlo in una direttiva `highlights` ... dovrò studiarmela. Nel caso migliore possiamo farlo col template stesso

**Comment by atorin** [comment]
OK, direi che in questo caso vogliamo fare le cose diversamente da upstream.

È necessario usare `highlights` perché questo è il modo in cui viene reso il sottotitolo nel nuovo tema: https://github.com/italia/docs-italia-theme/tree/bootstrap-italia/demo_docs/source

**Comment by danse** [comment]
come ho ribadito più volte, nel caso generale non possiamo cambiare il modo in cui i formati vengono convertite per andare incontro a quanto specificato nel tema, ognuno di questi cambiamenti richiede tempo. Comunque magari in questo caso è fattibile con i template. Ho assegnato la issue alla prossima milestone, sperando sia di semplice risoluzione come credo

**Comment by danse** [comment]
ecco la issue corrispondente su pandoc jgm/pandoc#4803

**Comment by danse** [comment]
dopo aver letto il codice mi sembra facile ottenere un sottotitolo in `highlights` come lo vogliamo, sull'adozione upstream si vedrà ma credo che la nostra richiesta sia assolutamente ragionevole

**Comment by danse** [comment]
questa issue richiederà più tempo del previsto visto che non basta usare i templates come speravo: c'è l'errore in pandoc da risolvere, poi c'è da aggiornare `converti` per usare un nostro template. questo potrebbe causare lo scivolamento di altre issues fuori dalla milestone, direi che potremmo rimandare #70 visto che è relativa ad una funzionalità aggiuntiva

**Comment by danse** [comment]
@yakky la soluzione di questa issue richiede l'aggiunta di un file nella home dell'utente che esegue `converti`. Vedo due opzioni:

- o aggiungiamo questa operazione alle altre eseguite via ansible
- o aggiungo un comando di installazione che può eseguire questa ed altre operazioni

il vantaggio della prima opzione è la rapidità, direi, mentre il vantaggio della seconda è una maggiore coesione del software, perché questa ed altre operazioni di installazione potrebbero essere coordinate in questo repo. che ne pensi? io non ho esperienza con ansible ma posso cominciare a familiarizzarmi con le regole in modo da verificare che l'installazione includa i passi previsti e magari in futuro proporre modifiche

**Comment by danse** [comment]
aggiungere uno script simile non mi richiede molto tempo, potrebbe essere pronto domani ... però quella che a me sembra coesione a te può sembrare opacità ... potresti voler gestire tutti gli assets via ansible

**Comment by yakky** [comment]
@danse secondo me la seconda potrebbe essere più sensata, così ``converti`` è libero di fare tutti i suoi setup e ansible deve solo lanciare questa inizializzazione ogni volta che viene aggiornato, senza conoscere i dettagli
perché altrimenti per ogni configurazione che vuoi aggiungere bisogna modificare due diversi repository e tenerly in sync., invece in questo modo ``converti`` è autonomo

**Comment by danse** [comment]
perfetto siamo d'accordo, grazie :+1:
