### ISSUE TITLE
Conversione di apici e virgolette nella versione ASCII

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-comandi-conversione#80]
Convertendo da Google Docs, il documento risulta pieno di apici inversi (backtick) e quote di tipo smart, tutti caratteri Unicode che sono considerati inutili da alcuni utenti, e rendono più complesso l’editing manuale

**Comment by danse** [comment]
@rasky allegheresti un link al Google Docs? hai convertito attraverso `.docx` o `.odt`, o altro formato?

**Comment by danse** [comment]
nel doc vedo le sostituzioni:

- `'` invece di `’`
- `"` invece di `“` e `”`
- `"\ *some italic text*\ "` invece di `“*some italic text*”`

**Comment by danse** [comment]
@rasky non capisco il motivo per cui hai aggiunto gli spazi fra quotes e asterischi, come all'ultimo punto dell'elenco puntato sopra. per esempio [qui](https://raw.githubusercontent.com/AgID/lg-acquisizione-e-riuso-software-per-pa-docs/master/riuso-software/introduzione-e-contesto-normativo.rst). ho provato `"*italic text*"` e funziona

**Comment by rasky** [comment]
ti risulta entrato con un mio commit? Pensavo fosse generato così dal convertitore in realtà

**Comment by danse** [comment]
ah non ho analizzato i commit ... dev'essere una versione vecchia del convertitore. problema risolto, grazie
