### ISSUE TITLE
direttiva toctree numbered 

### ISSUE THREAD

**Issue by pablopers** [italia/docs-italia-comandi-conversione#91]
Trovate che sia utile inserire nei risultati del comando converti, all'interno del file index la direttiva toctree "numbered" di default? Io personalmente l'ho trovata molto utile nell'applicazione ad un mio documento.

**Comment by danse** [comment]
penso che @atorin sia d'accordo

**Comment by atorin** [comment]
Io sono d'accordo. Ma più importante del mio parere è il fatto che `numbered` è richiesta dal nuovo tema per le didascalie di figure e tabelle.

**Comment by pablopers** [comment]
Valutate, giacché ci siete, se è il caso di inserire di default anche la direttiva `hidden`.

**Comment by danse** [comment]
per adesso aggiungerò `numbered`. non si tratta di direttive se capisco bene, ma di opzioni della direttiva _table of contents_

**Comment by danse** [comment]
è facile a livello di codice, però in alcuni dei test di conversione che abbiamo accumulato in https://github.com/danse/docs-italia-test-conversione, usare l'opzione `:numbered:` crea un effetto confusionario perché gli headers hanno già la loro numerazione. da quel che ho capito il tema non supporta questo caso, quindi comunque aggiungo `numbered` alla prima table of contents
