### ISSUE TITLE
Errore con la cartella di immagini

### ISSUE THREAD

**Issue by atorin** [italia/docs-italia-comandi-conversione#97]
Conversione di questo documento con il convertitore web:
[template.docx](https://github.com/italia/docs-italia-comandi-conversione/files/2315223/template.docx)

Il documento risultante ha due problemi con le immagini:
1. il link all'immagine è errato (il percorso usato non è corretto)
2. viene creata una cartella `index` con un'immagine dentro, ma questa cartella è inutile.

**Comment by danse** [comment]
l'immagine in `/immagini-e-tabelle/figura-con-didascalia.rst` punta a `.././media/image1.jpeg`. La parte `/./` potrebbe essere omessa, però il percorso sembra corretto e l'immagine appare quando costruisco lo sphinx ... @atorin mi sto perdendo qualcosa.

Siamo d'accordo sul fatto che l'immagine in `index/` sia superflua, ma qual'è il link errato?

**Comment by atorin** [comment]
Se converto il documento con il convertitore web, il percorso che viene fuori è `./media/image1.jpeg`.

Questo è il risultato che ottengo io:
[template.zip](https://github.com/italia/docs-italia-comandi-conversione/files/2319206/template.zip)

**Comment by danse** [comment]
oh, si tratta di qualcosa già descritto in #95, l'ho già risolto ma non ho ancora incluso le modifiche in una nuova release da portare sul servizio web. lascerò questa issue aperta finché la soluzione non sarà online

**Comment by danse** [comment]
poi c'è anche il problema con la cartella `index/` indesiderata
